### ISSUE TITLE
Confusion about "args.eval_batch_size"

### ISSUE THREAD

**Issue by xuzf-git** [yasumasaonoe/Box4Types#4]
https://github.com/yasumasaonoe/Box4Types/blob/00de4d89e55151da0c72fa776bb59f40e9ea03c8/box4et/main.py#L599

I am confused about this parameter, why is it not the case below：
```python
args.eval_batch_size = args.per_gpu_eval_batch_size * max(1, args.n_gpu) 
```

**Comment by yasumasaonoe** [comment]
Thanks for pointing out this!  I've fixed Line 599 and 883.
