### ISSUE TITLE
question about UFET dev set

### ISSUE THREAD

**Issue by yixiu1017** [yasumasaonoe/Box4Types#6]
Hello，thak you for release the code! UFET has three kinds of types (coarse, fine and ultra-fine), in your code, I don't know get macro-p, macro-r, macro-f1 of each kind of type (coarse, fine and ultra-fine).
Looking forward to your reply.
thank you very much !

**Comment by yasumasaonoe** [comment]
Hi, You can compute them using `[box4et/scorer.py](https://github.com/yasumasaonoe/Box4Types/blob/main/box4et/scorer.py)` (see [line 195-197](https://github.com/yasumasaonoe/Box4Types/blob/0dd92eacf8e077352c89d864d1bd39576d41079c/box4et/scorer.py#L195)).
